### ISSUE TITLE
Inverted information in the trade bot list

### ISSUE THREAD

**Issue by 27aume** [KomodoPlatform/BarterDEX#95] opened 2018-02-03 08:58 UTC
GUI doesnt lay the information properly
 (I think)
Using the trade bot to BID work fine and list
right information ( upper bot in my list)
Using it with ASK shows inverted information.
should be 
Total to Buy: 0.00449055 BEER
Total Spending: 44.91 PIZZA

![bdex_swp_bot_inverted data in bot list](https://user-images.githubusercontent.com/30743589/35765654-e58f8ef2-089e-11e8-9670-eceb5224eacc.jpg)

**Comment by 27aume** [comment] 2018-02-03 09:07
Bot list must be able to take in account that there is 2 way of placing both type of order. 
because of the switch pairs.
like e.g.
a ask on BEER / PIZZA
is the same then a BID PIZZA/ BEER

I think the bot list don't take this in account

**Comment by siulynot** [comment] 2018-03-15 01:56
Closing this since its a duplicate of issue #70

**Closed** 2018-03-15 01:57 UTC
Labels: duplicate
