### ISSUE TITLE
App Crashes / Freezes when trying to enable Experimental Features

### ISSUE THREAD

**Issue by jcity** [KomodoPlatform/BarterDEX#44] opened 2018-01-08 07:31 UTC
I'm on `v0.8`

The stack trace is:
```
{ command: 'update_settings',
  data: 
   { deflang: 'en_US',
     dev: false,
     experimentalFeatures: true,
     theme: 'dark' } }
{ deflang: 'en_US',
  dev: false,
  experimentalFeatures: true,
  theme: 'dark' }
{ command: 'read_settings' }
ZeroConf claim log updated!
SyntaxError: /Users/justinmyers/Library/Application Support/BarterDEX/settings.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Users/justinmyers/Justin/Crypto/BarterDEX/node_modules/fs-extra/node_modules/jsonfile/index.js:33:18
    at /Users/justinmyers/Justin/Crypto/BarterDEX/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)
```

`grewalsatinder` says: "Setting json need fix"

**Comment by satindergrewal** [comment] 2018-01-08 11:43
Duplicate of https://github.com/KomodoPlatform/BarterDEX/issues/30

**Closed by satindergrewal** 2018-01-08 11:43 UTC
